### ISSUE TITLE
Fix composer autoload issue

### ISSUE THREAD

**Issue by alexroan** [alexroan/twitter-scraper#1]
Warning: require_once(../../vendor/autoload.php): failed to open stream: No such file or directory in /www/wordpress/wp-content/plugins/easy_twitter_feeder/vendor/alexroan/twitter-scraper/src/alexroan/TwitterScraper.php on line 4

**Comment by wijourdil** [comment]
The autoload error still exist, I forked the project and created a PR to fix this issue : https://github.com/alexroan/twitter-scraper/pull/2

**Comment by alexroan** [comment]
20dd542
